Update patch set 3
Patch Set 3:

This change broke compilation of x86 (32-bit) kernels:

block/built-in.o: In function `blk_latency_hist_show':
kernel/common/block/blk-core.c:3580: undefined reference to `__udivdi3'
kernel/common/block/blk-core.c:3589: undefined reference to `__udivdi3'
kernel/common/block/blk-core.c:3605: undefined reference to `__udivdi3'
kernel/common/block/blk-core.c:3614: undefined reference to `__udivdi3'

I guess you introduced a 64-bit divide without using do_div64() or similar, but I haven't looked at the code..

Patch-set: 3