Update patch set 1
Patch Set 1:

This commit breaks my build and is supposed to depend on 49f7f31ab27d which was somehow missed.

ipc/util.c: In function ‘ipc_rcu_alloc’:
ipc/util.c:485:12: error: ‘struct ipc_rcu’ has no member named ‘data’
  return out->data;
            ^
In file included from include/linux/spinlock.h:384:0,
                 from include/linux/mmzone.h:7,
                 from include/linux/gfp.h:4,
                 from include/linux/mm.h:8,
                 from ipc/util.c:20:
ipc/util.c: In function ‘ipc_rcu_getref’:
include/linux/kernel.h:784:27: error: ‘struct ipc_rcu’ has no member named ‘data’
  const typeof( ((type *)0)->member ) *__mptr = (ptr); \
                           ^
include/linux/atomic.h:28:52: note: in definition of macro ‘atomic_inc_not_zero’
 #define atomic_inc_not_zero(v)  atomic_add_unless((v), 1, 0)
                                                    ^
ipc/util.c:490:30: note: in expansion of macro ‘container_of’
  return atomic_inc_not_zero(&container_of(ptr, struct ipc_rcu, data)->refcount);
                              ^
include/linux/compiler-gcc4.h:14:34: error: ‘struct ipc_rcu’ has no member named ‘data’
 #define __compiler_offsetof(a,b) __builtin_offsetof(a,b)
                                  ^
include/linux/atomic.h:28:52: note: in definition of macro ‘atomic_inc_not_zero’
 #define atomic_inc_not_zero(v)  atomic_add_unless((v), 1, 0)
                                                    ^
include/linux/stddef.h:17:31: note: in expansion of macro ‘__compiler_offsetof’
 #define offsetof(TYPE,MEMBER) __compiler_offsetof(TYPE,MEMBER)
                               ^
include/linux/kernel.h:785:29: note: in expansion of macro ‘offsetof’
  (type *)( (char *)__mptr - offsetof(type,member) );})
                             ^
ipc/util.c:490:30: note: in expansion of macro ‘container_of’
  return atomic_inc_not_zero(&container_of(ptr, struct ipc_rcu, data)->refcount);

In file included from include/asm-generic/bug.h:13:0,
                 from arch/arm/include/asm/bug.h:59,
                 from include/linux/bug.h:4,
                 from include/linux/thread_info.h:11,
                 from include/linux/preempt.h:9,
                 from include/linux/spinlock.h:50,
                 from include/linux/mmzone.h:7,
                 from include/linux/gfp.h:4,
                 from include/linux/mm.h:8,
                 from ipc/util.c:20:
ipc/util.c: In function ‘ipc_rcu_putref’:
include/linux/kernel.h:784:27: error: ‘struct ipc_rcu’ has no member named ‘data’
  const typeof( ((type *)0)->member ) *__mptr = (ptr); \
                           ^
ipc/util.c:495:22: note: in expansion of macro ‘container_of’
  struct ipc_rcu *p = container_of(ptr, struct ipc_rcu, data);
                      ^
In file included from include/linux/compiler-gcc.h:103:0,
                 from include/linux/compiler.h:54,
                 from include/uapi/linux/stddef.h:1,
                 from include/linux/stddef.h:4,
                 from include/uapi/linux/posix_types.h:4,
                 from include/uapi/linux/types.h:13,
                 from include/linux/types.h:5,
                 from include/linux/thread_info.h:10,
                 from include/linux/preempt.h:9,
                 from include/linux/spinlock.h:50,
                 from include/linux/mmzone.h:7,
                 from include/linux/gfp.h:4,
                 from include/linux/mm.h:8,
                 from ipc/util.c:20:
include/linux/compiler-gcc4.h:14:34: error: ‘struct ipc_rcu’ has no member named ‘data’
 #define __compiler_offsetof(a,b) __builtin_offsetof(a,b)
                                  ^
include/linux/stddef.h:17:31: note: in expansion of macro ‘__compiler_offsetof’
 #define offsetof(TYPE,MEMBER) __compiler_offsetof(TYPE,MEMBER)
                               ^
include/linux/kernel.h:785:29: note: in expansion of macro ‘offsetof’
  (type *)( (char *)__mptr - offsetof(type,member) );})
                             ^
ipc/util.c:495:22: note: in expansion of macro ‘container_of’
  struct ipc_rcu *p = container_of(ptr, struct ipc_rcu, data);
                      ^
ipc/util.c: In function ‘ipc_rcu_alloc’:
ipc/util.c:486:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
ipc/util.c: In function ‘ipc_rcu_getref’:
ipc/util.c:491:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make[1]: *** [ipc/util.o] Error 1
make: *** [ipc] Error 2

Patch-set: 1
Reviewer: Leon Yu <1053739@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Verified=0