jbd: fix ext3 build
Ext3 build is broken and acknowledged so by a recent ext4/crypto backport
commit "ext4: insert 3.18 version of fs/ext4, fs/jbd2 and associated
header files", Change-Id: I9e3d96227cc7b7aa44f7b69a368771bba17ccd56.

----------
  CC      fs/ext3/balloc.o
In file included from include/linux/jbd.h:247:0,
                 from fs/ext3/ext3.h:23,
                 from fs/ext3/balloc.c:16:
include/linux/jbd_common.h: In function ‘jbd_lock_bh_state’:
include/linux/jbd_common.h:18:16: error: ‘BH_State’ undeclared (first use in this function)
include/linux/jbd_common.h:18:16: note: each undeclared identifier is reported only once for each function it appears in
include/linux/jbd_common.h: In function ‘jbd_trylock_bh_state’:
include/linux/jbd_common.h:23:26: error: ‘BH_State’ undeclared (first use in this function)
include/linux/jbd_common.h: In function ‘jbd_is_locked_bh_state’:
include/linux/jbd_common.h:28:28: error: ‘BH_State’ undeclared (first use in this function)
include/linux/jbd_common.h: In function ‘jbd_unlock_bh_state’:
include/linux/jbd_common.h:33:18: error: ‘BH_State’ undeclared (first use in this function)
include/linux/jbd_common.h: In function ‘jbd_lock_bh_journal_head’:
include/linux/jbd_common.h:38:16: error: ‘BH_JournalHead’ undeclared (first use in this function)
include/linux/jbd_common.h: In function ‘jbd_unlock_bh_journal_head’:
include/linux/jbd_common.h:43:18: error: ‘BH_JournalHead’ undeclared (first use in this function)
  CC      drivers/clk/clkdev.o
make[2]: *** [fs/ext3/balloc.o] Error 1
make[1]: *** [fs/ext3] Error 2
make[1]: *** Waiting for unfinished jobs....
----------

This patch contain hand picked changes from mainline commit
b34090e5e22a "jbd2: refine waiting for shadow buffers", which seem
to fix the Ext3 build. We probably do not need all these changes but
a similar set of changes went into jbd2 as part of above mentioned
Ext4 backport commit. So I copied all the changes for jbd as well.

Change-Id: Ib594d43767ed835e95407f54bacc7b18a83dddac
Signed-off-by: Amit Pundir <amit.pundir@linaro.org>