cpufreq: interactive: replace strict_strtoul() with kstrtoul()
strict_strtoul() is obsolete. Use kstrtoul() instead
as per the upstream commit 9d8abf45944e "IB/srpt:
replace strict_strtoul() with kstrtoul()", otherwise
we run into following build error:

  CC      drivers/cpufreq/cpufreq_interactive.o
drivers/cpufreq/cpufreq_interactive.c: In function ‘store_hispeed_freq’:
drivers/cpufreq/cpufreq_interactive.c:784:2: error: implicit declaration of function ‘strict_strtoul’ [-Werror=implicit-function-declaration]
cc1: some warnings being treated as errors
make[2]: *** [drivers/cpufreq/cpufreq_interactive.o] Error 1

Signed-off-by: Amit Pundir <amit.pundir@linaro.org>