USB: Android: Use correct struct name for bmAttributes variable
This patch fixes a compilation issue on the USB Android gadget:

CC drivers/usb/gadget/android.o
drivers/usb/gadget/android.c: In function 'android_bind':
drivers/usb/gadget/android.c:198: error: 'android_config' undeclared

This bug was introduced by the following commit:

USB: android gadget: add remote wakeup attribute ...
f1e654d503322cff19154658d2bce0901aceda05

Signed-off-by: Leed Aguilar <leed.aguilar@ti.com>
Signed-off-by: Vikram Pandita <vikram.pandita@ti.com>